# Blog config
theme: jekyll-theme-minimal
title: "Duality Docs"
description: "Developer manual for the Duality game engine"
google_analytics: UA-39997821-2

# External links, to be displayed in the top
links:
  - title: 'Project'
    url: 'https://duality.adamslair.net'
  - title: 'Forum'
    url: 'https://forum.adamslair.net'
  - title: 'Chat'
    url: 'http://chat.adamslair.net'

# Top-Level categories, to be displayed in the nav overview
categories:
  - id: 'introduction'
    title: 'Introduction'
  - id: 'tutorials'
    title: 'Tutorials'
  - id: 'basics'
    title: 'Basic Topics'
  - id: 'advanced'
    title: 'Advanced Topics'
  - id: 'contributing'
    title: 'Contributing'